import Head from "next/head";
import Link from "next/link";
import Layout from "../components/layout";

import styles from "../styles/Home.module.css";

import prisma from "../lib/prisma";

import { getSortedListsData } from "../lib/lists";
import { getAllBookData } from "../lib/books";
// Executes first. Calls getSortedListsData, which returns an array of
// objects that include the id (filename in /lists) and the associated data.
// Then returns an object with a props key, which has an object with a key
// called allListsData, whose value is the aforementioned array of objects
// i.e.:
// props: {
//     {
//         allListsData: [{ id: "growth-studies", title: "Growth Studies" }];
//     }
// }
export async function getStaticProps() {
    // const feed = await prisma.post.findMany({
    //     where: { published: true },
    //     include: {
    //         author: {
    //             select: { name: true },
    //         },
    //     },
    // });
    const allListsData = getSortedListsData();
    const allBookData = getAllBookData();
    return {
        props: {
            feed,
            allListsData,
            allBookData,
        },
    };
}

// After getStaticProps is executed, it'll populate props (hence why `props: {...}` is mandatory)
// Once that's done, the React component can render
export default function Home(props) {
    // console.log(props.feed);
    return (
        <Layout>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>
                    <div>Let&apos;s take a look at our lists!</div>

                    {props.allListsData.map(({ id, title }) => (
                        <li key={id}>
                            <Link href={`/lists/${id}`}>
                                <a>{title}</a>
                            </Link>
                        </li>
                    ))}
                    <br />
                    {/* {props.feed.map((i, j) => (
                        <div key={j}>{i.title}</div>
                    ))} */}
                </main>

                <footer className={styles.footer}>Footer</footer>
            </div>
        </Layout>
    );
}
